name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update system
      run: sudo apt update

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install ngrok -y

    - name: Auth ngrok
      run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable SSH
      run: |
        sudo apt install openssh-server -y
        sudo systemctl enable ssh
        sudo systemctl start ssh

    - name: Set SSH password
      run: |
        echo "runner:password123" | sudo chpasswd

    - name: Start ngrok tunnel
      run: ngrok tcp 22
